baseURL = "https://pierre.aboucaya.name/"
languageCode = "fr"
title = "Pierre Aboucaya"

# Theme
theme = "github.com/forestryio/hugo-theme-novela"

paginate = 6

[social]
twitter= "https://twitter.com/pierreaboucaya"
github= "https://github.com/asper"
linkedin= "https://www.linkedin.com/pierreaboucaya"
instagram = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"